image: docker:latest
services:
- docker:dind

variables:
  DOCKER_DRIVER: overlay
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -B"
  DEPLOY_PROJECT: "yogstation-ping"

stages:
- build
- release
- staging

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
  - target/
  - .m2/repository

build:
  stage: build
  image: maven:3.6.0-jdk-8-alpine
  script:
  - 'mvn $MAVEN_CLI_OPTS package'
  artifacts:
    paths:
    - target/

release:
  stage: release
  before_script:
  - 'cp target/$DEPLOY_PROJECT.jar app.jar'
  script:
  - 'docker build -t registry.gitlab.com/ashcorr20/yogstationweb/$DEPLOY_PROJECT .'
  - 'docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com'
  - 'docker push registry.gitlab.com/ashcorr20/yogstationweb/$DEPLOY_PROJECT'
  only:
    variables:
    - $DEPLOY_PROJECT
Deploy To Staging:
  stage: staging
  image: alpine
  script:
  - apk add --no-cache curl
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - mv ./kubectl /usr/local/bin/kubectl
  - kubectl config set-cluster deploycluster --server="$KUBE_URL" --insecure-skip-tls-verify=true
  - kubectl config set-credentials admin --token="$KUBE_TOKEN"
  - kubectl config set-context default --cluster=deploycluster --user=admin
  - kubectl config use-context default
  - 'printf "apiVersion: v1\nkind: Secret\n$(kubectl create secret docker-registry gitlab-registry --docker-server=$CI_REGISTRY --docker-username=$CI_REGISTRY_USER --docker-password=$CI_REGISTRY_PASSWORD --docker-email=$GITLAB_USER_EMAIL -o yaml --dry-run)" | kubectl apply -f -'
  - sed 's/_APP_NAME_/'"$DEPLOY_PROJECT"'/g; s/_APP_NAMESPACE_/'"yogs-staging"'/g; s/_VERSION_/'"$CI_COMMIT_SHA"'/g' kubernetes.tpl.yml > kubernetes.yml;
  - kubectl apply -f kubernetes.yml
  only:
    variables:
    - $DEPLOY_PROJECT
  when: manual